#!/bin/bash

declare -a args

for i in "$@"
do
    if [[ "$i" != -march* ]]; then
        args+=("$i")
    fi
done

if [[ -z "$PORTABLE_X64_ARCH" ]]; then
    ARCH=skylake-avx512
else
    ARCH=$PORTABLE_X64_ARCH
fi

if [[ $(uname -m) == "aarch64" ]]; then
    ARCH=armv8-a
fi

/usr/bin/g++_real -march=$ARCH "${args[@]}"
