name: Publish Docker and WSL Images

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        config-inline: |
          [worker.oci]
            max-parallelism = 1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Use the repository information of the checked-out code to format docker tags
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: pierotofy/odm
        tag-semver: |
          {{version}}
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./portable.Dockerfile
        platforms: linux/amd64 #,linux/arm64
        push: true
        no-cache: true
        tags: |
          ${{ steps.docker_meta.outputs.tags }}
          pierotofy/odm:latest
    # Trigger NodeODM build
    - name: Dispatch NodeODM Build Event
      id: nodeodm_dispatch
      run: |
        curl -X POST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/pierotofy/NodeODM/actions/workflows/publish-docker.yaml/dispatches --data '{"ref": "master"}'