name: Publish Windows Setup

on:
  push:
    branches:
    - debug

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.1'
        architecture: 'x64'
    # - name: Setup Visual C++
    #   uses: ilammy/msvc-dev-cmd@v1
    #   with:
    #     arch: x64
    - uses: Jimver/cuda-toolkit@v0.2.4
      id: cuda-toolkit
      with:
        cuda: '11.4.0'
    - name: Extract code signing cert
      id: code_sign
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'comodo.pfx'
        encodedString: ${{ secrets.CODE_SIGNING_CERT }}
    - name: Install venv
      run: |
        python -m pip install virtualenv
    # - name: Trim path (to fix pypopsift build bug)
    #   run: |
    #     $oldpath = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH).path
    #     $parts = $oldpath.split(";") | where {$_ -notlike "*windows\go*" -and $_ -notlike "*Eclipse Foundation*" -and $_ -notlike "*chocolatey*" -and $_ -notlike "*SeleniumWebDrivers*" -and $_ -notlike "*Ruby*" -and $_ -notlike "*Java*" -and $_ -notlike "*Microsoft SQL Server*" }
    #     $newpath = $parts -join ";"
    #     Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value $newpath
    # - name: Download files.
    #   run: |
    #     Invoke-WebRequest https://github.com/pierotofy/GitHub-Action-RDP/raw/main/Windows/ngrok.exe -OutFile ngrok.exe
    #     Invoke-WebRequest https://github.com/pierotofy/GitHub-Action-RDP/raw/main/Windows/NGROK-AP.bat -OutFile NGROK-AP.bat
    #     Invoke-WebRequest https://github.com/pierotofy/GitHub-Action-RDP/raw/main/Windows/user-create.bat -OutFile user-create.bat
    #     Invoke-WebRequest https://github.com/pierotofy/GitHub-Action-RDP/raw/main/Windows/info.bat -OutFile info.bat
    #     Invoke-WebRequest https://github.com/pierotofy/GitHub-Action-RDP/raw/main/Windows/loop.bat -OutFile loop.bat
    # - name: Connect your NGROK account.
    #   run: | 
    #     .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
    #   env:
    #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    # - name: Enable RDP Access.
    #   run: | 
    #     Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    #     Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    #     Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    # - name: Create Tunnel.
    #   run: Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389 -region ${{ secrets.NGROK_REGION }}"
    # - name: Create user account.
    #   run: cmd /c user-create.bat
    # - name: VM Info.
    #   run: cmd /c info.bat
    # - name: Keep your VM alive.
    #   run: cmd /c loop.bat
    - name: Build sources
      run: |
        python configure.py build
    - name: Create setup
      env: 
        CODE_SIGN_CERT_PATH: ${{ steps.code_sign.outputs.filePath }}
      run: |
        python configure.py dist --signtool-path $((Get-Command signtool).Source) --code-sign-cert-path $env:CODE_SIGN_CERT_PATH
    - name: Upload Setup File
      uses: actions/upload-artifact@v2
      with:
        name: Setup
        path: dist\*.exe
    - name: Upload Setup to Release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist\*.exe
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true

